spring:
  application:
    name: studentRecordSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/studentDB
    username: postgres
    password: ubuntu123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/changelog.xml